project_name             = "twin"
environment              = "prod"
bedrock_model_id         = "apac.amazon.nova-lite-v1:0"
bedrock_fallback_model_id = "apac.amazon.nova-micro-v1:0"
llm_provider             = "bedrock"
lambda_timeout           = 60
api_throttle_burst_limit = 20
api_throttle_rate_limit  = 10
use_custom_domain        = false
root_domain              = ""  # Replace with your actual domain
